---
name: Jupyter 
category: Interactive Apps
subcategory: Servers
role: batch_connect
description: |
  This app will launch a Jupyter server on one or more nodes.
  <p style="color:red;font-size=40px;">
  <b>Due to the decommission of the Loomis filesystem, we have migrated all data stored in your Loomis project directory to the Gibbs filesystem. Unfortunately, due to the migration, most conda environments will need to be rebuilt. Please see the following page for instructions on rebuilding your environment(s):</b><br>
  https://docs.ycrc.yale.edu/clusters-at-yale/guides/conda-clone/
  </p>

